// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Schedules {
    public enum GetFilterQueryParameterType {
        [EnumMember(Value = "monday")]
        Monday,
        [EnumMember(Value = "tuesday")]
        Tuesday,
        [EnumMember(Value = "wednesday")]
        Wednesday,
        [EnumMember(Value = "thursday")]
        Thursday,
        [EnumMember(Value = "friday")]
        Friday,
        [EnumMember(Value = "saturday")]
        Saturday,
        [EnumMember(Value = "sunday")]
        Sunday,
        [EnumMember(Value = "unknown")]
        Unknown,
        [EnumMember(Value = "other")]
        Other,
    }
}
