// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Schedules {
    public enum GetSfwQueryParameterType {
        [EnumMember(Value = "true")]
        True,
        [EnumMember(Value = "false")]
        False,
    }
}
