// <auto-generated/>
using JikanRest.Genres.Anime;
using JikanRest.Genres.Manga;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace JikanRest.Genres {
    /// <summary>
    /// Builds and executes requests for operations under \genres
    /// </summary>
    public class GenresRequestBuilder : BaseRequestBuilder {
        /// <summary>The anime property</summary>
        public AnimeRequestBuilder Anime { get =>
            new AnimeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manga property</summary>
        public MangaRequestBuilder Manga { get =>
            new MangaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new GenresRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GenresRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/genres", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new GenresRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GenresRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/genres", rawUrl) {
        }
    }
}
