// <auto-generated/>
using JikanRest.Users.Userbyid.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace JikanRest.Users.Userbyid {
    /// <summary>
    /// Builds and executes requests for operations under \users\userbyid
    /// </summary>
    public class UserbyidRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the JikanRest.users.userbyid.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public UserbyidItemRequestBuilder this[int position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("id", position);
            return new UserbyidItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new UserbyidRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserbyidRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/userbyid", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new UserbyidRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserbyidRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/userbyid", rawUrl) {
        }
    }
}
