// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Users.Item.History {
    public enum GetTypeQueryParameterType {
        [EnumMember(Value = "anime")]
        Anime,
        [EnumMember(Value = "manga")]
        Manga,
    }
}
