BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Show";
CREATE TABLE IF NOT EXISTS "Show" (
	"Id"	GUID NOT NULL UNIQUE,
	"Url"	TEXT,
	"Name"	TEXT,
	"Runtime"	INTEGER,
	"AverageRuntime"	INTEGER,
	"Premiered"	TEXT,
	"Ended"	TEXT,
	"OfficialSite"	TEXT,
	"Weight"	INTEGER,
	"Summary"	TEXT,
	"Updated"	INTEGER,
	PRIMARY KEY("Id")
);

DROP TABLE IF EXISTS "Status";
CREATE TABLE IF NOT EXISTS "Status" (
	"Id"	GUID NOT NULL UNIQUE,
	"Name"	TEXT,
	PRIMARY KEY("Id")
);

DROP TABLE IF EXISTS "Language";
CREATE TABLE IF NOT EXISTS "Language" (
	"Id"	GUID NOT NULL UNIQUE,
	"Name"	TEXT,
	PRIMARY KEY("Id")
);
DROP TABLE IF EXISTS "Genere";
CREATE TABLE IF NOT EXISTS "Genere" (
	"Id"	GUID NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("Id")
);

DROP TABLE IF EXISTS "ShowGenere";
CREATE TABLE IF NOT EXISTS "ShowGenere" (
	"Id"	GUID NOT NULL UNIQUE,
	"ShowId"	GUID NOT NULL,
	"GenereId"	GUID NOT NULL,
	PRIMARY KEY ("Id"),
	FOREIGN KEY ("ShowId") REFERENCES "Show"("Id") ON DELETE CASCADE,
	FOREIGN KEY ("GenereId") REFERENCES "Genere"("Id") ON DELETE CASCADE
);
DROP TABLE IF EXISTS "ShowLanguage";
CREATE TABLE IF NOT EXISTS "ShowLanguage" (
	"Id"	GUID NOT NULL UNIQUE,
	"ShowId"	GUID NOT NULL,
	"LanguageId"	GUID NOT NULL,
	PRIMARY KEY ("Id"),
	FOREIGN KEY ("ShowId") REFERENCES "Show"("Id") ON DELETE CASCADE,
	FOREIGN KEY ("LanguageId") REFERENCES "Language"("Id") ON DELETE CASCADE
);
DROP TABLE IF EXISTS "ShowStatus";
CREATE TABLE IF NOT EXISTS "ShowStatus" (
	"Id"	GUID NOT NULL UNIQUE,
	"ShowId"	GUID NOT NULL,
	"StatusId"	GUID NOT NULL,
	PRIMARY KEY ("Id"),
	FOREIGN KEY ("ShowId") REFERENCES "Show"("Id") ON DELETE CASCADE,
	FOREIGN KEY ("StatusId") REFERENCES "Status"("Id") ON DELETE CASCADE
);
COMMIT;