// <auto-generated/>
using JikanRest.Characters.Item.Anime;
using JikanRest.Characters.Item.Full;
using JikanRest.Characters.Item.Manga;
using JikanRest.Characters.Item.Pictures;
using JikanRest.Characters.Item.Voices;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace JikanRest.Characters.Item {
    /// <summary>
    /// Builds and executes requests for operations under \characters\{id}
    /// </summary>
    public class CharactersItemRequestBuilder : BaseRequestBuilder {
        /// <summary>The anime property</summary>
        public AnimeRequestBuilder Anime { get =>
            new AnimeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The full property</summary>
        public FullRequestBuilder Full { get =>
            new FullRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manga property</summary>
        public MangaRequestBuilder Manga { get =>
            new MangaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pictures property</summary>
        public PicturesRequestBuilder Pictures { get =>
            new PicturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The voices property</summary>
        public VoicesRequestBuilder Voices { get =>
            new VoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new CharactersItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CharactersItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/characters/{id}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new CharactersItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CharactersItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/characters/{id}", rawUrl) {
        }
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<CharactersGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default) {
#nullable restore
#else
        public async Task<CharactersGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default) {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<CharactersGetResponse>(requestInfo, CharactersGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default) {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default) {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public CharactersItemRequestBuilder WithUrl(string rawUrl) {
            return new CharactersItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
