export default {
  BASE_ARUPPI: 'https://aruppi.jeluchu.xyz/',
  BASE_ANIMEFLV: 'https://www3.animeflv.net/',
  BASE_MONOSCHINOS: 'https://monoschinos2.com/',
  BASE_TIOANIME: 'https://tioanime.com/',
  BASE_JKANIME: 'https://jkanime.net/',
  BASE_ANIMEFLV_JELU: 'https://aruppi.jeluchu.xyz/apis/animeflv/v1/',
  BASE_YOUTUBE: 'https://aruppi.jeluchu.xyz/api/Youtube/?channelId=',
  BASE_YOUTUBE_PLAYLIST: 'https://aruppi.jeluchu.xyz/api/Youtube/playlist/?playlistId=',
  BASE_JIKAN: 'https://aruppi.jeluchu.xyz/apis/jikan/v3/',
  BASE_IVOOX: 'https://www.ivoox.com/podcast-anitakume_fg_f1660716_filtro_1.xml',
  BASE_KUDASAI: 'https://somoskudasai.com/feed/',
  BASE_RAMENPARADOS: 'https://ramenparados.com/category/noticias/anime/feed/',
  BASE_CRUNCHYROLL: 'https://www.crunchyroll.com/newsrss?lang=esES',
  JKANIME_SEARCH: 'https://jkanime.net/buscar/',
  ANIMEFLV_SEARCH: 'https://animeflv.net/browse?',
  SEARCH_DIRECTORY: 'https://animeflv.net/browse?order=title&page=',
  BASE_EPISODE_IMG_URL: 'https://cdn.animeflv.net/screenshots/',
  BASE_QWANT: 'https://api.qwant.com/v3/search/images?',
  REDDIT_ANIMETHEMES: 'https://reddit.com/r/AnimeThemes/wiki/',
  BASE_THEMEMOE: 'https://themes.moe/api/',
  BASE_ARUPPI_MONOSCHINOS: 'https://aruppi.jeluchu.xyz/apis/monoschinos/',
};
