// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Seasons.Now {
    public enum GetFilterQueryParameterType {
        [EnumMember(Value = "tv")]
        Tv,
        [EnumMember(Value = "movie")]
        Movie,
        [EnumMember(Value = "ova")]
        Ova,
        [EnumMember(Value = "special")]
        Special,
        [EnumMember(Value = "ona")]
        Ona,
        [EnumMember(Value = "music")]
        Music,
    }
}
