// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Available Anime audience ratings&lt;br&gt;&lt;br&gt;&lt;b&gt;Ratings&lt;/b&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt;G - All Ages&lt;/li&gt;&lt;li&gt;PG - Children&lt;/li&gt;&lt;li&gt;PG-13 - Teens 13 or older&lt;/li&gt;&lt;li&gt;R - 17+ (violence &amp; profanity)&lt;/li&gt;&lt;li&gt;R+ - Mild Nudity&lt;/li&gt;&lt;li&gt;Rx - Hentai&lt;/li&gt;&lt;/ul&gt;</summary>
    public enum Anime_search_query_rating {
        [EnumMember(Value = "g")]
        G,
        [EnumMember(Value = "pg")]
        Pg,
        [EnumMember(Value = "pg13")]
        Pg13,
        [EnumMember(Value = "r17")]
        R17,
        [EnumMember(Value = "r")]
        R,
        [EnumMember(Value = "rx")]
        Rx,
    }
}
