// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Airing status</summary>
    public enum Anime_full_status {
        [EnumMember(Value = "Finished Airing")]
        FinishedAiring,
        [EnumMember(Value = "Currently Airing")]
        CurrentlyAiring,
        [EnumMember(Value = "Not yet aired")]
        NotYetAired,
    }
}
