// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Available Anime statuses</summary>
    public enum Anime_search_query_status {
        [EnumMember(Value = "airing")]
        Airing,
        [EnumMember(Value = "complete")]
        Complete,
        [EnumMember(Value = "upcoming")]
        Upcoming,
    }
}
