// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Season</summary>
    public enum Anime_full_season {
        [EnumMember(Value = "summer")]
        Summer,
        [EnumMember(Value = "winter")]
        Winter,
        [EnumMember(Value = "spring")]
        Spring,
        [EnumMember(Value = "fall")]
        Fall,
    }
}
