// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Anime Type</summary>
    public enum Anime_type {
        [EnumMember(Value = "TV")]
        TV,
        [EnumMember(Value = "OVA")]
        OVA,
        [EnumMember(Value = "Movie")]
        Movie,
        [EnumMember(Value = "Special")]
        Special,
        [EnumMember(Value = "ONA")]
        ONA,
        [EnumMember(Value = "Music")]
        Music,
    }
}
