// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Anime audience rating</summary>
    public enum Anime_full_rating {
        [EnumMember(Value = "G - All Ages")]
        GAllAges,
        [EnumMember(Value = "PG - Children")]
        PGChildren,
        [EnumMember(Value = "PG-13 - Teens 13 or older")]
        PG13Teens13OrOlder,
        [EnumMember(Value = "R - 17+ (violence & profanity)")]
        R17_plus_ViolenceProfanity,
        [EnumMember(Value = "R+ - Mild Nudity")]
        R_plus_MildNudity,
        [EnumMember(Value = "Rx - Hentai")]
        RxHentai,
    }
}
