// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Club Search Query OrderBy</summary>
    public enum Club_search_query_orderby {
        [EnumMember(Value = "mal_id")]
        Mal_id,
        [EnumMember(Value = "name")]
        Name,
        [EnumMember(Value = "members_count")]
        Members_count,
        [EnumMember(Value = "created")]
        Created,
    }
}
