// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Club Category</summary>
    public enum Club_category {
        [EnumMember(Value = "actors & artists")]
        ActorsArtists,
        [EnumMember(Value = "anime")]
        Anime,
        [EnumMember(Value = "characters")]
        Characters,
        [EnumMember(Value = "cities & neighborhoods")]
        CitiesNeighborhoods,
        [EnumMember(Value = "companies")]
        Companies,
        [EnumMember(Value = "conventions")]
        Conventions,
        [EnumMember(Value = "games")]
        Games,
        [EnumMember(Value = "japan")]
        Japan,
        [EnumMember(Value = "manga")]
        Manga,
        [EnumMember(Value = "music")]
        Music,
        [EnumMember(Value = "others")]
        Others,
        [EnumMember(Value = "schools")]
        Schools,
    }
}
