// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Club Search Query Category</summary>
    public enum Club_search_query_category {
        [EnumMember(Value = "anime")]
        Anime,
        [EnumMember(Value = "manga")]
        Manga,
        [EnumMember(Value = "actors_and_artists")]
        Actors_and_artists,
        [EnumMember(Value = "characters")]
        Characters,
        [EnumMember(Value = "cities_and_neighborhoods")]
        Cities_and_neighborhoods,
        [EnumMember(Value = "companies")]
        Companies,
        [EnumMember(Value = "conventions")]
        Conventions,
        [EnumMember(Value = "games")]
        Games,
        [EnumMember(Value = "japan")]
        Japan,
        [EnumMember(Value = "music")]
        Music,
        [EnumMember(Value = "other")]
        Other,
        [EnumMember(Value = "schools")]
        Schools,
    }
}
