// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Filter genres by type</summary>
    public enum Genre_query_filter {
        [EnumMember(Value = "genres")]
        Genres,
        [EnumMember(Value = "explicit_genres")]
        Explicit_genres,
        [EnumMember(Value = "themes")]
        Themes,
        [EnumMember(Value = "demographics")]
        Demographics,
    }
}
