// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Order by magazine data</summary>
    public enum Magazines_query_orderby {
        [EnumMember(Value = "mal_id")]
        Mal_id,
        [EnumMember(Value = "name")]
        Name,
        [EnumMember(Value = "count")]
        Count,
    }
}
