// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Available Manga order_by properties</summary>
    public enum Manga_search_query_orderby {
        [EnumMember(Value = "mal_id")]
        Mal_id,
        [EnumMember(Value = "title")]
        Title,
        [EnumMember(Value = "start_date")]
        Start_date,
        [EnumMember(Value = "end_date")]
        End_date,
        [EnumMember(Value = "chapters")]
        Chapters,
        [EnumMember(Value = "volumes")]
        Volumes,
        [EnumMember(Value = "score")]
        Score,
        [EnumMember(Value = "scored_by")]
        Scored_by,
        [EnumMember(Value = "rank")]
        Rank,
        [EnumMember(Value = "popularity")]
        Popularity,
        [EnumMember(Value = "members")]
        Members,
        [EnumMember(Value = "favorites")]
        Favorites,
    }
}
