// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Available Manga statuses</summary>
    public enum Manga_search_query_status {
        [EnumMember(Value = "publishing")]
        Publishing,
        [EnumMember(Value = "complete")]
        Complete,
        [EnumMember(Value = "hiatus")]
        Hiatus,
        [EnumMember(Value = "discontinued")]
        Discontinued,
        [EnumMember(Value = "upcoming")]
        Upcoming,
    }
}
