// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace JikanRest.Models {
    public class Manga_images : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Available images in JPG</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Manga_images_jpg? Jpg { get; set; }
#nullable restore
#else
        public Manga_images_jpg Jpg { get; set; }
#endif
        /// <summary>Available images in WEBP</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Manga_images_webp? Webp { get; set; }
#nullable restore
#else
        public Manga_images_webp Webp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new manga_images and sets the default values.
        /// </summary>
        public Manga_images() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Manga_images CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Manga_images();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"jpg", n => { Jpg = n.GetObjectValue<Manga_images_jpg>(Manga_images_jpg.CreateFromDiscriminatorValue); } },
                {"webp", n => { Webp = n.GetObjectValue<Manga_images_webp>(Manga_images_webp.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<Manga_images_jpg>("jpg", Jpg);
            writer.WriteObjectValue<Manga_images_webp>("webp", Webp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
