// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Manga Type</summary>
    public enum Manga_type {
        [EnumMember(Value = "Manga")]
        Manga,
        [EnumMember(Value = "Novel")]
        Novel,
        [EnumMember(Value = "Light Novel")]
        LightNovel,
        [EnumMember(Value = "One-shot")]
        OneShot,
        [EnumMember(Value = "Doujinshi")]
        Doujinshi,
        [EnumMember(Value = "Manhua")]
        Manhua,
        [EnumMember(Value = "Manhwa")]
        Manhwa,
        [EnumMember(Value = "OEL")]
        OEL,
    }
}
