// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace JikanRest.Models {
    /// <summary>
    /// Person Resource
    /// </summary>
    public class Person_full : IAdditionalDataHolder, IParsable {
        /// <summary>Biography</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? About { get; set; }
#nullable restore
#else
        public string About { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Other Names</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AlternateNames { get; set; }
#nullable restore
#else
        public List<string> AlternateNames { get; set; }
#endif
        /// <summary>The anime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Person_full_anime>? Anime { get; set; }
#nullable restore
#else
        public List<Person_full_anime> Anime { get; set; }
#endif
        /// <summary>Birthday Date ISO8601</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Birthday { get; set; }
#nullable restore
#else
        public string Birthday { get; set; }
#endif
        /// <summary>Family Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FamilyName { get; set; }
#nullable restore
#else
        public string FamilyName { get; set; }
#endif
        /// <summary>Number of users who have favorited this entry</summary>
        public int? Favorites { get; set; }
        /// <summary>Given Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GivenName { get; set; }
#nullable restore
#else
        public string GivenName { get; set; }
#endif
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public People_images? Images { get; set; }
#nullable restore
#else
        public People_images Images { get; set; }
#endif
        /// <summary>MyAnimeList ID</summary>
        public int? MalId { get; set; }
        /// <summary>The manga property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Person_full_manga>? Manga { get; set; }
#nullable restore
#else
        public List<Person_full_manga> Manga { get; set; }
#endif
        /// <summary>Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>MyAnimeList URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The voices property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Person_full_voices>? Voices { get; set; }
#nullable restore
#else
        public List<Person_full_voices> Voices { get; set; }
#endif
        /// <summary>Person&apos;s website URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebsiteUrl { get; set; }
#nullable restore
#else
        public string WebsiteUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new person_full and sets the default values.
        /// </summary>
        public Person_full() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Person_full CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Person_full();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"about", n => { About = n.GetStringValue(); } },
                {"alternate_names", n => { AlternateNames = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"anime", n => { Anime = n.GetCollectionOfObjectValues<Person_full_anime>(Person_full_anime.CreateFromDiscriminatorValue)?.ToList(); } },
                {"birthday", n => { Birthday = n.GetStringValue(); } },
                {"family_name", n => { FamilyName = n.GetStringValue(); } },
                {"favorites", n => { Favorites = n.GetIntValue(); } },
                {"given_name", n => { GivenName = n.GetStringValue(); } },
                {"images", n => { Images = n.GetObjectValue<People_images>(People_images.CreateFromDiscriminatorValue); } },
                {"mal_id", n => { MalId = n.GetIntValue(); } },
                {"manga", n => { Manga = n.GetCollectionOfObjectValues<Person_full_manga>(Person_full_manga.CreateFromDiscriminatorValue)?.ToList(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"url", n => { Url = n.GetStringValue(); } },
                {"voices", n => { Voices = n.GetCollectionOfObjectValues<Person_full_voices>(Person_full_voices.CreateFromDiscriminatorValue)?.ToList(); } },
                {"website_url", n => { WebsiteUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("about", About);
            writer.WriteCollectionOfPrimitiveValues<string>("alternate_names", AlternateNames);
            writer.WriteCollectionOfObjectValues<Person_full_anime>("anime", Anime);
            writer.WriteStringValue("birthday", Birthday);
            writer.WriteStringValue("family_name", FamilyName);
            writer.WriteIntValue("favorites", Favorites);
            writer.WriteStringValue("given_name", GivenName);
            writer.WriteObjectValue<People_images>("images", Images);
            writer.WriteIntValue("mal_id", MalId);
            writer.WriteCollectionOfObjectValues<Person_full_manga>("manga", Manga);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("url", Url);
            writer.WriteCollectionOfObjectValues<Person_full_voices>("voices", Voices);
            writer.WriteStringValue("website_url", WebsiteUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
