// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Top items filter types</summary>
    public enum Top_anime_filter {
        [EnumMember(Value = "airing")]
        Airing,
        [EnumMember(Value = "upcoming")]
        Upcoming,
        [EnumMember(Value = "bypopularity")]
        Bypopularity,
        [EnumMember(Value = "favorite")]
        Favorite,
    }
}
