// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Top items filter types</summary>
    public enum Top_manga_filter {
        [EnumMember(Value = "publishing")]
        Publishing,
        [EnumMember(Value = "upcoming")]
        Upcoming,
        [EnumMember(Value = "bypopularity")]
        Bypopularity,
        [EnumMember(Value = "favorite")]
        Favorite,
    }
}
