// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Users Search Query Gender.</summary>
    public enum Users_search_query_gender {
        [EnumMember(Value = "any")]
        Any,
        [EnumMember(Value = "male")]
        Male,
        [EnumMember(Value = "female")]
        Female,
        [EnumMember(Value = "nonbinary")]
        Nonbinary,
    }
}
