// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace JikanRest.Models {
    public class Anime_videos_data : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The episodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Anime_videos_data_episodes>? Episodes { get; set; }
#nullable restore
#else
        public List<Anime_videos_data_episodes> Episodes { get; set; }
#endif
        /// <summary>The music_videos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Anime_videos_data_music_videos>? MusicVideos { get; set; }
#nullable restore
#else
        public List<Anime_videos_data_music_videos> MusicVideos { get; set; }
#endif
        /// <summary>The promo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Anime_videos_data_promo>? Promo { get; set; }
#nullable restore
#else
        public List<Anime_videos_data_promo> Promo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new anime_videos_data and sets the default values.
        /// </summary>
        public Anime_videos_data() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Anime_videos_data CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Anime_videos_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"episodes", n => { Episodes = n.GetCollectionOfObjectValues<Anime_videos_data_episodes>(Anime_videos_data_episodes.CreateFromDiscriminatorValue)?.ToList(); } },
                {"music_videos", n => { MusicVideos = n.GetCollectionOfObjectValues<Anime_videos_data_music_videos>(Anime_videos_data_music_videos.CreateFromDiscriminatorValue)?.ToList(); } },
                {"promo", n => { Promo = n.GetCollectionOfObjectValues<Anime_videos_data_promo>(Anime_videos_data_promo.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<Anime_videos_data_episodes>("episodes", Episodes);
            writer.WriteCollectionOfObjectValues<Anime_videos_data_music_videos>("music_videos", MusicVideos);
            writer.WriteCollectionOfObjectValues<Anime_videos_data_promo>("promo", Promo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
