// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Available Anime types</summary>
    public enum Anime_search_query_type {
        [EnumMember(Value = "tv")]
        Tv,
        [EnumMember(Value = "movie")]
        Movie,
        [EnumMember(Value = "ova")]
        Ova,
        [EnumMember(Value = "special")]
        Special,
        [EnumMember(Value = "ona")]
        Ona,
        [EnumMember(Value = "music")]
        Music,
        [EnumMember(Value = "cm")]
        Cm,
        [EnumMember(Value = "pv")]
        Pv,
        [EnumMember(Value = "tv_special")]
        Tv_special,
    }
}
