// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Available Manga types</summary>
    public enum Manga_search_query_type {
        [EnumMember(Value = "manga")]
        Manga,
        [EnumMember(Value = "novel")]
        Novel,
        [EnumMember(Value = "lightnovel")]
        Lightnovel,
        [EnumMember(Value = "oneshot")]
        Oneshot,
        [EnumMember(Value = "doujin")]
        Doujin,
        [EnumMember(Value = "manhwa")]
        Manhwa,
        [EnumMember(Value = "manhua")]
        Manhua,
    }
}
