// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Publishing status</summary>
    public enum Manga_full_status {
        [EnumMember(Value = "Finished")]
        Finished,
        [EnumMember(Value = "Publishing")]
        Publishing,
        [EnumMember(Value = "On Hiatus")]
        OnHiatus,
        [EnumMember(Value = "Discontinued")]
        Discontinued,
        [EnumMember(Value = "Not yet published")]
        NotYetPublished,
    }
}
