// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>Available People order_by properties</summary>
    public enum People_search_query_orderby {
        [EnumMember(Value = "mal_id")]
        Mal_id,
        [EnumMember(Value = "name")]
        Name,
        [EnumMember(Value = "birthday")]
        Birthday,
        [EnumMember(Value = "favorites")]
        Favorites,
    }
}
