// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>The type of reviews to filter by. Defaults to anime.</summary>
    public enum Top_reviews_type_enum {
        [EnumMember(Value = "anime")]
        Anime,
        [EnumMember(Value = "manga")]
        Manga,
    }
}
