// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JikanRest.Models {
    /// <summary>User&apos;s anime list status filter options</summary>
    public enum User_anime_list_status_filter {
        [EnumMember(Value = "all")]
        All,
        [EnumMember(Value = "watching")]
        Watching,
        [EnumMember(Value = "completed")]
        Completed,
        [EnumMember(Value = "onhold")]
        Onhold,
        [EnumMember(Value = "dropped")]
        Dropped,
        [EnumMember(Value = "plantowatch")]
        Plantowatch,
    }
}
