// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace JikanRest.Clubs.Item.Members {
    public class MembersGetResponse_pagination : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The has_next_page property</summary>
        public bool? HasNextPage { get; set; }
        /// <summary>The last_visible_page property</summary>
        public int? LastVisiblePage { get; set; }
        /// <summary>
        /// Instantiates a new membersGetResponse_pagination and sets the default values.
        /// </summary>
        public MembersGetResponse_pagination() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static MembersGetResponse_pagination CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new MembersGetResponse_pagination();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"has_next_page", n => { HasNextPage = n.GetBoolValue(); } },
                {"last_visible_page", n => { LastVisiblePage = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("has_next_page", HasNextPage);
            writer.WriteIntValue("last_visible_page", LastVisiblePage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
