// <auto-generated/>
using JikanRest.Top.Anime;
using JikanRest.Top.Characters;
using JikanRest.Top.Manga;
using JikanRest.Top.People;
using JikanRest.Top.Reviews;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace JikanRest.Top {
    /// <summary>
    /// Builds and executes requests for operations under \top
    /// </summary>
    public class TopRequestBuilder : BaseRequestBuilder {
        /// <summary>The anime property</summary>
        public AnimeRequestBuilder Anime { get =>
            new AnimeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The characters property</summary>
        public CharactersRequestBuilder Characters { get =>
            new CharactersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manga property</summary>
        public MangaRequestBuilder Manga { get =>
            new MangaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The people property</summary>
        public PeopleRequestBuilder People { get =>
            new PeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reviews property</summary>
        public ReviewsRequestBuilder Reviews { get =>
            new ReviewsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new TopRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TopRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/top", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new TopRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TopRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/top", rawUrl) {
        }
    }
}
