// <auto-generated/>
using JikanRest.Seasons.Item.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace JikanRest.Seasons.Item {
    /// <summary>
    /// Builds and executes requests for operations under \seasons\{year}
    /// </summary>
    public class WithYearItemRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the JikanRest.seasons.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithSeasonItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("season", position);
            return new WithSeasonItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new WithYearItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithYearItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/seasons/{year}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new WithYearItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithYearItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/seasons/{year}", rawUrl) {
        }
    }
}
